name: Paparazzo
options:
  bundleIdPrefix: avito
  deploymentTarget:
    iOS: 9.0
targets:
  Paparazzo:
    type: framework
    platform: iOS
    sources: 
      - Paparazzo/Assets
      - Paparazzo/Core
      - Paparazzo/Localization
    dependencies:
      - carthage: JNWSpringAnimation
      - framework: ImageSource
  ImageSource:
    platform: iOS
    type: framework
    sources: 
      - ImageSource/AlamofireImage
      - ImageSource/Core
      - ImageSource/Local
      - ImageSource/PHAsset
      - ImageSource/Remote
      - ImageSource/UIKit
    dependencies:
      - carthage: Alamofire
      - carthage: AlamofireImage
